# Generated by Django 5.2.8 on 2025-11-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libranian',
            new_name='Librarian',
        ),
    ]
