# Generated by Django 5.2.8 on 2025-11-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_rename_libranian_librarian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='books',
            new_name='books_collection',
        ),
        migrations.AddField(
            model_name='book',
            name='library_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_fks', to='relationship_app.library'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=2000),
        ),
    ]
